Name: Product
Host: 0.0.0.0
Port: 8001

Mysql:
  DataSource: root:1234abc.@tcp(127.0.0.1:3306)/mall?charset=utf8mb4&parseTime=true
CacheRedis:
  - Host: 0.0.0.0:6379
    Type: node
    Pass:
Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

ProductRpc:
  Etcd:
    Hosts:
      - 0.0.0.0:2379
    Key: product.rpc

Prometheus:
  Host: 0.0.0.0
  Port: 9081
  Path: /metrics