Name: product.rpc
ListenOn: 0.0.0.0:9001
Mode: dev
Etcd:
  Hosts:
  - 0.0.0.0:2379
  Key: product.rpc


Mysql:
  DataSource: root:1234abc.@tcp(127.0.0.1:3306)/mall?charset=utf8mb4&parseTime=true
CacheRedis:
  - Host: 0.0.0.0:6379
    Type: node
    Pass:

Prometheus:
  Host: 0.0.0.0
  Port: 9091
  Path: /metrics